const fs = require('fs');

function getArgValue(argv, flag) {
  const idx = argv.indexOf(flag);
  if (idx === -1) return null;
  return argv[idx + 1] ?? null;
}

function phaseFromPrompt(prompt) {
  if (!prompt) return 'UNKNOWN';
  if (prompt.includes('PHASE: PLAN')) return 'PLAN';
  if (prompt.includes('PHASE: REVIEW_CANDIDATES')) return 'REVIEW_CANDIDATES';
  if (prompt.includes('PHASE: HANDOFF')) return 'HANDOFF';
  if (prompt.includes('PHASE: ANSWER_EXECUTOR')) return 'ANSWER_EXECUTOR';
  return 'UNKNOWN';
}

function extractFirstCandidateId(prompt) {
  // Candidates are rendered as:
  // candidate_id: <id>
  const m = prompt.match(/candidate_id:\s*([^\s]+)/);
  return m ? m[1] : null;
}

function main() {
  const argv = process.argv.slice(2);
  const prompt = getArgValue(argv, '-p') || '';
  const phase = phaseFromPrompt(prompt);

  let structured_output;

  if (phase === 'PLAN') {
    structured_output = {
      status: 'OK',
      claude_prompt: [
        'You are the executor. Implement the change in this repository.',
        '',
        'Goal:',
        '- Fix division by zero behavior in `src/divide.js` so it throws `new Error("Division by zero")` when b===0.',
        '',
        'Constraints:',
        '- Make minimal change required.',
        '- Do not modify tests; just make them pass.',
        '',
        'Then run:',
        '- node scripts/unit_test.js',
        '- node scripts/e2e_test.js',
      ].join('\n'),
      test_commands: [
        { id: 'unit', kind: 'unit', label: null, command: ['node', 'scripts/unit_test.js'], timeout_sec: null },
        { id: 'e2e', kind: 'e2e', label: null, command: ['node', 'scripts/e2e_test.js'], timeout_sec: null },
      ],
      tasks: [
        {
          id: '1',
          title: 'Throw on division by zero',
          description:
            'Update src/divide.js so divide(a,b) throws Error("Division by zero") when b===0, preserving normal division otherwise.',
          acceptance_criteria: ['unit tests pass', 'e2e tests pass'],
          suggested_commands: ['node scripts/unit_test.js', 'node scripts/e2e_test.js'],
        },
      ],
      questions: [],
      notes: 'Mock plan generated by tests/mocks/claude_reviewer_mock.js',
    };
  } else if (phase === 'ANSWER_EXECUTOR') {
    structured_output = {
      status: 'ANSWER',
      answer: 'Throw `new Error("Division by zero")` when b===0. Keep normal division otherwise.',
      questions: [],
      notes: 'Mock reviewer answer generated by tests/mocks/claude_reviewer_mock.js',
    };
  } else if (phase === 'REVIEW_CANDIDATES' || phase === 'HANDOFF') {
    const winner = extractFirstCandidateId(prompt);
    structured_output = {
      status: 'APPROVED',
      winner_candidate_id: winner,
      summary: phase === 'HANDOFF' ? 'Handoff: change approved and persisted.' : 'Approved best candidate.',
      feedback: 'Looks good.',
      next_prompt: null,
      questions: [],
      notes: 'Mock reviewer decision generated by tests/mocks/claude_reviewer_mock.js',
    };
  } else {
    console.error(`claude_reviewer_mock: unknown phase. Prompt:\n${prompt}`);
    process.exit(2);
  }

  const output = {
    session_id: 'mock-session-claude-reviewer',
    result: `claude_reviewer_mock: ${phase}`,
    structured_output,
  };

  process.stdout.write(JSON.stringify(output));
}

main();

